apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedabbas96/charts.git
    path: istio/base
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  ignoreDifferences:
    - kind: MutatingWebhookConfiguration
      group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/0/failurePolicy
        - /webhooks/1/failurePolicy
        - /webhooks/2/failurePolicy
        - /webhooks/3/failurePolicy
        - /webhooks/4/failurePolicy
    - kind: ValidatingWebhookConfiguration
      group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/0/failurePolicy
        - /webhooks/1/failurePolicy
        - /webhooks/2/failurePolicy
        - /webhooks/3/failurePolicy
        - /webhooks/4/failurePolicy
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
